"""OSCAL assessment plan emission for CapableDeputy controls."""

from __future__ import annotations

import json
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from capabledeputy.compliance.oscal import build_control_mapping


def build_assessment_plan(
    *,
    system_security_plan_href: str = "./capdep-ssp.json",
    evidence_bundle_href: str = "./capdep-evidence.json",
    audit_replay_href: str = "./capdep-audit-replay.json",
    capdep_version: str = "unknown",
    custom_mapping: dict[str, list[str]] | None = None,
) -> dict[str, Any]:
    """Build a small OSCAL Assessment Plan v1.1.2.

    The plan names each mapped control and points auditors at the
    replayable audit/evidence artifacts generated by the companion
    commands. It is intentionally procedural and operator-runnable.
    """
    impls = build_control_mapping(custom_mapping)
    controls = sorted({cid for impl in impls for cid in impl.nist_controls})
    return {
        "assessment-plan": {
            "uuid": str(uuid.uuid4()),
            "metadata": {
                "title": "CapableDeputy Assessment Plan",
                "last-modified": datetime.now(UTC).isoformat(),
                "version": capdep_version,
                "oscal-version": "1.1.2",
            },
            "import-ssp": {"href": system_security_plan_href},
            "local-definitions": {
                "objectives-and-methods": [
                    {
                        "uuid": str(uuid.uuid4()),
                        "control-id": control_id,
                        "description": (
                            "Replay CapableDeputy audit events, verify the "
                            "tamper-evident chain separately, and compare "
                            "policy decisions against the control evidence bundle."
                        ),
                        "props": [
                            {
                                "name": "evidence-bundle",
                                "value": evidence_bundle_href,
                                "ns": "https://capabledeputy.io/ns/oscal/v1",
                            },
                            {
                                "name": "audit-replay",
                                "value": audit_replay_href,
                                "ns": "https://capabledeputy.io/ns/oscal/v1",
                            },
                        ],
                    }
                    for control_id in controls
                ],
            },
            "reviewed-controls": {
                "control-selections": [{"include-controls": [{"control-id": c} for c in controls]}],
            },
            "assessment-subjects": [
                {
                    "type": "component",
                    "description": (
                        "CapableDeputy daemon, policy engine, substrate ports, and audit log."
                    ),
                },
            ],
            "tasks": [
                {
                    "uuid": str(uuid.uuid4()),
                    "type": "evidence-validation",
                    "title": "Replay audit evidence",
                    "description": (
                        "Run capdep compliance-audit-replay over the audit log and "
                        "verify no sandbox region remains undiscarded and no policy "
                        "decision rule is unmapped."
                    ),
                },
            ],
        },
    }


def emit_assessment_plan(
    output_path: Path,
    *,
    system_security_plan_href: str = "./capdep-ssp.json",
    evidence_bundle_href: str = "./capdep-evidence.json",
    audit_replay_href: str = "./capdep-audit-replay.json",
    capdep_version: str = "unknown",
    custom_mapping: dict[str, list[str]] | None = None,
) -> None:
    plan = build_assessment_plan(
        system_security_plan_href=system_security_plan_href,
        evidence_bundle_href=evidence_bundle_href,
        audit_replay_href=audit_replay_href,
        capdep_version=capdep_version,
        custom_mapping=custom_mapping,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(plan, indent=2, sort_keys=True), encoding="utf-8")
